// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: catalog.proto

package catalog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	// ValidateProduct checks if a product exists and is available for purchase
	ValidateProduct(ctx context.Context, in *ProductValidationRequest, opts ...grpc.CallOption) (*ProductValidationResponse, error)
	// GetProductPrice fetches current product price for cart calculations
	GetProductPrice(ctx context.Context, in *ProductPriceRequest, opts ...grpc.CallOption) (*ProductPriceResponse, error)
	// ValidateCartItems validates multiple products in a single call for efficiency
	ValidateCartItems(ctx context.Context, in *CartValidationRequest, opts ...grpc.CallOption) (*CartValidationResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ValidateProduct(ctx context.Context, in *ProductValidationRequest, opts ...grpc.CallOption) (*ProductValidationResponse, error) {
	out := new(ProductValidationResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/ValidateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProductPrice(ctx context.Context, in *ProductPriceRequest, opts ...grpc.CallOption) (*ProductPriceResponse, error) {
	out := new(ProductPriceResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/GetProductPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ValidateCartItems(ctx context.Context, in *CartValidationRequest, opts ...grpc.CallOption) (*CartValidationResponse, error) {
	out := new(CartValidationResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/ValidateCartItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility
type CatalogServiceServer interface {
	// ValidateProduct checks if a product exists and is available for purchase
	ValidateProduct(context.Context, *ProductValidationRequest) (*ProductValidationResponse, error)
	// GetProductPrice fetches current product price for cart calculations
	GetProductPrice(context.Context, *ProductPriceRequest) (*ProductPriceResponse, error)
	// ValidateCartItems validates multiple products in a single call for efficiency
	ValidateCartItems(context.Context, *CartValidationRequest) (*CartValidationResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatalogServiceServer struct {
}

func (UnimplementedCatalogServiceServer) ValidateProduct(context.Context, *ProductValidationRequest) (*ProductValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateProduct not implemented")
}
func (UnimplementedCatalogServiceServer) GetProductPrice(context.Context, *ProductPriceRequest) (*ProductPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductPrice not implemented")
}
func (UnimplementedCatalogServiceServer) ValidateCartItems(context.Context, *CartValidationRequest) (*CartValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCartItems not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_ValidateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ValidateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/ValidateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ValidateProduct(ctx, req.(*ProductValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProductPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProductPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/GetProductPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProductPrice(ctx, req.(*ProductPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ValidateCartItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ValidateCartItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/ValidateCartItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ValidateCartItems(ctx, req.(*CartValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateProduct",
			Handler:    _CatalogService_ValidateProduct_Handler,
		},
		{
			MethodName: "GetProductPrice",
			Handler:    _CatalogService_GetProductPrice_Handler,
		},
		{
			MethodName: "ValidateCartItems",
			Handler:    _CatalogService_ValidateCartItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
