apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: catalog
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        monitoring.kubelab.lan/scrape: "true"  # Enable Prometheus metrics collection
      annotations:
        # Loki log collection annotations
        loki.grafana.com/scrape: "true"
        loki.grafana.com/log-format: "json"
        # Prometheus metrics annotations
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: catalog
        image: catalog-service:latest
        imagePullPolicy: Never  # Use local image built by Tilt
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: grpc
        env:
        # Application configuration
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: "postgres.catalog.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "localmart"
        - name: DB_USER
          value: "catalog_user"
        - name: DB_PASSWORD
          value: "catalog_pass"
        # OpenTelemetry configuration
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "alloy-otlp.monitoring.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "catalog-service"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.0"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=development,service.namespace=catalog"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi 