# Set a simple admin password
adminPassword: "password"

# Pre-configure the Prometheus and Loki data sources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: DS_PROMETHEUS
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local # K8s DNS name for the Prometheus service
        access: proxy
        isDefault: true
      - name: DS_LOKI
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100 # K8s DNS name for the Loki service
        access: proxy
      - name: DS_TEMPO
        type: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200 # K8s DNS name for the Tempo service
        access: proxy
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: 'DS_LOKI'
            filterByTraceID: true
            filterBySpanID: false
            tags: ['job', 'instance', 'pod', 'namespace']
          tracesToMetrics:
            datasourceUid: 'DS_PROMETHEUS'
            tags: [{ key: 'service.name', value: 'service' }, { key: 'service.namespace', value: 'namespace' }]
          serviceMap:
            datasourceUid: 'DS_PROMETHEUS'

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'grafana-dashboards-kubernetes'
      orgId: 1
      folder: 'Kubernetes'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
# Automatically discover and load dashboards from ConfigMaps
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard # Tell the sidecar to look for ConfigMaps with this label
    defaultFolderName: "General"
    labelValue: "1"
    folderAnnotation: grafana_folder
    searchNamespace: ALL
    provider:
      foldersFromFilesStructure: true
dashboards: # we can also load dashboards from URLs
  grafana-dashboards-kubernetes:
    k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ''