apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-route
  namespace: monitoring
spec:
  entryPoints: ["web"]
  routes:
    - match: Host(`prometheus.kubelab.lan`)
      kind: Rule
      services:
        - name: prometheus-server
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  entryPoints: ["web"]
  routes:
    - match: Host(`grafana.kubelab.lan`)
      kind: Rule
      services:
        - name: grafana
          port: 80